name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        name: Build & Deploy
        runs-on: ubuntu-latest
        steps:
            # --- SETUP ---
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            # --- BUILD ---
            - name: Build project
              run: npm run build

            # --- PREPARE TUNNEL ---
            - name: Install cloudflared
              run: |
                  curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
                  sudo dpkg -i cloudflared.deb

            - name: Setup SSH Key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519

            - name: Configure SSH Proxy
              run: |
                  echo "Host vm_via_tunnel" >> ~/.ssh/config
                  echo "  HostName ${{ secrets.VM_HOSTNAME }}" >> ~/.ssh/config
                  echo "  User ${{ secrets.USERNAME }}" >> ~/.ssh/config
                  echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
                  echo "  ProxyCommand /usr/bin/cloudflared access ssh --hostname %h --id ${{ secrets.CF_ACCESS_CLIENT_ID }} --secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" >> ~/.ssh/config
                  echo "  StrictHostKeyChecking no" >> ~/.ssh/config

            # --- DEPLOY ---
            - name: Rsync Files to VM
              run: |
                  # Deploys to the "docusaurus-deploy" folder inside your user's home directory.
                  # The --delete flag ensures old files are removed from the target.

                  rsync -avz --delete \
                    -e "ssh" \
                    ./build/ \
                    vm_via_tunnel:~/cpm/docs/build/

            - name: Discord notification
              uses: Ilshidur/action-discord@master
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              with:
                  args: "A new version of the docs has been built and deployed."
